site_name: HDI Challenge Documentation

nav:
  - Home: index.md
  - Quick Start Guide: quickstart.md
  - Initialization Guide: initialization.md
  - Project Configuration: configuration.md
  - API Reference: api.md
  - Command Line Interface: commands.md
  - Standard Deployment Guide: deploy.md
  - Load Testing: stress_test.md
  - Unit Testing: unit_test.md
  - Coverage Test: coverage.md
  - Security Analysis: bandit.md
  - License Agreement: licence.md

plugins:
  - mkdocstrings

theme: readthedocs
