[tool.ruff]
line-length = 88
indent-width = 4
include = ["pyproject.toml"]
extend-include = ["*.ipynb"]
exclude = [
    ".git",
    ".ipynb_checkpoints",
    ".venv",
    ".vscode",
    "logs",
    "artifacts",
    "notebooks",
    "misc",
    "**/__pycache__",
    "**/__init__.py",
    "pipes",
    "data",
    "tests",
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
exclude = ["__init__.py"]
quote-style = "single"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v -ra -q"
log_cli = true
log_level = "DEBUG"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_file = "logs/test-logs.txt"
log_file_level = "INFO"
filterwarnings = "ignore"

[tool.coverage.run]
source = ["modules", "tests"]
omit = [
    "*/ipykernel_*.py",
    "*/site-packages/*",
    "/usr/lib/*",
]

[tool.bandit]
exclude_dirs = [
    "tests",
    "docs",
    "logs",
    "artifacts",
    "notebooks",
    "misc",
    "**/__pycache__",
    "**/__init__.py",
    "pipes",
    "data",
    ".venv",
]
tests = ["B201", "B301"]
skips = ["B101", "B601"]
